/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewCliente extends javax.swing.JPanel {

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_clave = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellido_p = new javax.swing.JLabel();
        jl_apellido_m = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cliente = new javax.swing.JTable();
        jl_titulo = new javax.swing.JLabel();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jtf_clave_cliente = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido_paterno = new javax.swing.JTextField();
        jtf_apellido_materno = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_clave.setText("Clave de cliente");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jl_nombre.setText("Nombre ");
        add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jl_apellido_p.setText("Apellido paterno");
        add(jl_apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jl_apellido_m.setText("Apellido Materno");
        add(jl_apellido_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jl_telefono.setText("Telefono");
        add(jl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jt_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jt_cliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 610, 100));

        jl_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 2, 18)); // NOI18N
        jl_titulo.setText("          Clientes");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 20));

        jbtn_primero.setText("<<<");
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jbtn_ultimo.setText(">>>");
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jbtn_anterior.setText("Anterior");
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 80, -1));

        jbtn_siguiente.setText("Siguiente");
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jbtn_nuevo.setText("Nuevo");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 80, -1));

        jbtn_actualizar.setText("Actualizar");
        add(jbtn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        jbtn_eliminar.setText("Eliminar");
        add(jbtn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, -1));

        jbtn_agregar.setText("Agregar");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 230, 80, -1));
        add(jtf_clave_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 60, -1));
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));
        add(jtf_apellido_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));
        add(jtf_apellido_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, -1));
        add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, 20));
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Pictures\\deposito\\depositphotos_37862899-stock-photo-coca-cola-fanta-and-sprite.jpg")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 730, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jtbn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbn_ultimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_apellido_m;
    public javax.swing.JLabel jl_apellido_p;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_cliente;
    public javax.swing.JTextField jtf_apellido_materno;
    public javax.swing.JTextField jtf_apellido_paterno;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_cliente;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
