/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewDeposito extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeposito
     */
    public ViewDeposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jmb_menu = new javax.swing.JMenuBar();
        jmregistro = new javax.swing.JMenu();
        jmi_login = new javax.swing.JMenuItem();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_producto = new javax.swing.JMenuItem();
        jmi_proveedor = new javax.swing.JMenuItem();
        jmi_usuarios = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();
        jmventa = new javax.swing.JMenu();
        jmi_venta = new javax.swing.JMenuItem();
        jmi_compras = new javax.swing.JMenuItem();
        jmenu_deta = new javax.swing.JMenu();
        jmi_deta_venta = new javax.swing.JMenuItem();
        jmi_deta_compra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/cocaclasic.jpg"))); // NOI18N
        jPanel1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/coca negro.jpg"))); // NOI18N
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 450));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 470, 490));

        jmregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-menú-principal-50.png"))); // NOI18N
        jmregistro.setText("Registros ");

        jmi_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-identificación-no-verificada-50.png"))); // NOI18N
        jmi_login.setText("Login");
        jmregistro.add(jmi_login);

        jmi_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-carpeta-de-usuario-50.png"))); // NOI18N
        jmi_cliente.setText("Clientes");
        jmregistro.add(jmi_cliente);

        jmi_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-caja-llena-50.png"))); // NOI18N
        jmi_producto.setText("Producto");
        jmregistro.add(jmi_producto);

        jmi_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-proveedor-50.png"))); // NOI18N
        jmi_proveedor.setText("Proveedor");
        jmregistro.add(jmi_proveedor);

        jmi_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-usuario-de-género-neutro-50 (1).png"))); // NOI18N
        jmi_usuarios.setText("Usuarios");
        jmregistro.add(jmi_usuarios);

        jmi_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-salir-redondeado-50.png"))); // NOI18N
        jmi_salir.setText("Salir");
        jmregistro.add(jmi_salir);

        jmb_menu.add(jmregistro);

        jmventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-terminal-punto-de-venta-50.png"))); // NOI18N
        jmventa.setText("Venta y compra");

        jmi_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-venta-50.png"))); // NOI18N
        jmi_venta.setText("Ventas");
        jmventa.add(jmi_venta);

        jmi_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-orden-de-compra-50.png"))); // NOI18N
        jmi_compras.setText("Compras");
        jmventa.add(jmi_compras);

        jmb_menu.add(jmventa);

        jmenu_deta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-ver-detalles-48.png"))); // NOI18N
        jmenu_deta.setText("Detalles Venta y Compra");

        jmi_deta_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-orden-de-compra-50.png"))); // NOI18N
        jmi_deta_venta.setText("Detalles Venta");
        jmenu_deta.add(jmi_deta_venta);

        jmi_deta_compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-orden-de-compra-48.png"))); // NOI18N
        jmi_deta_compra.setText("Detalles Compra");
        jmenu_deta.add(jmi_deta_compra);

        jmb_menu.add(jmenu_deta);

        setJMenuBar(jmb_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JMenuBar jmb_menu;
    public javax.swing.JMenu jmenu_deta;
    public javax.swing.JMenuItem jmi_cliente;
    public javax.swing.JMenuItem jmi_compras;
    public javax.swing.JMenuItem jmi_deta_compra;
    public javax.swing.JMenuItem jmi_deta_venta;
    public javax.swing.JMenuItem jmi_login;
    public javax.swing.JMenuItem jmi_producto;
    public javax.swing.JMenuItem jmi_proveedor;
    public javax.swing.JMenuItem jmi_salir;
    public javax.swing.JMenuItem jmi_usuarios;
    public javax.swing.JMenuItem jmi_venta;
    public javax.swing.JMenu jmregistro;
    public javax.swing.JMenu jmventa;
    // End of variables declaration//GEN-END:variables
}
