/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewProducto extends javax.swing.JPanel {

    /**
     * Creates new form ViewProducto
     */
    public ViewProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_clave = new javax.swing.JLabel();
        jl_producto = new javax.swing.JLabel();
        jl_contenido = new javax.swing.JLabel();
        jl_existencias = new javax.swing.JLabel();
        jl_clave_proveedor = new javax.swing.JLabel();
        jl_precio_pz = new javax.swing.JLabel();
        jl_paquete24 = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jtf_clave_producto = new javax.swing.JTextField();
        jtf_tipo_producto = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        jtf_existencias = new javax.swing.JTextField();
        jtf_clave_proveedor = new javax.swing.JTextField();
        jtf_precio_pz = new javax.swing.JTextField();
        jtf_paquete24 = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_clave.setText("Clave de producto");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jl_producto.setText("Producto");
        add(jl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        jl_contenido.setText("Contenido");
        add(jl_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jl_existencias.setText("Existencias");
        add(jl_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jl_clave_proveedor.setText("Clave de Proveedor");
        add(jl_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jl_precio_pz.setText("Precio por pz");
        add(jl_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jl_paquete24.setText("Precio por paquete24");
        add(jl_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jl_titulo.setFont(new java.awt.Font("PMingLiU-ExtB", 2, 14)); // NOI18N
        jl_titulo.setText("Registro de Productos ");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, 146, -1));

        jt_productos.setBackground(new java.awt.Color(0, 102, 102));
        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Producto", "Contenido", "Existencias", "Proveedor", "Precio Pz", "Paquete24"
            }
        ));
        jScrollPane1.setViewportView(jt_productos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 680, 180));

        jtf_clave_producto.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_producto.setBorder(null);
        add(jtf_clave_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        jtf_tipo_producto.setBackground(new java.awt.Color(0, 102, 102));
        jtf_tipo_producto.setBorder(null);
        add(jtf_tipo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, -1));

        jtf_contenido.setBackground(new java.awt.Color(0, 102, 102));
        jtf_contenido.setBorder(null);
        add(jtf_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, -1));

        jtf_existencias.setBackground(new java.awt.Color(0, 102, 102));
        jtf_existencias.setBorder(null);
        add(jtf_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        jtf_clave_proveedor.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_proveedor.setBorder(null);
        add(jtf_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, -1));

        jtf_precio_pz.setBackground(new java.awt.Color(0, 102, 102));
        jtf_precio_pz.setBorder(null);
        add(jtf_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, -1));

        jtf_paquete24.setBackground(new java.awt.Color(0, 102, 102));
        jtf_paquete24.setBorder(null);
        add(jtf_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jtf_buscar.setBackground(new java.awt.Color(0, 102, 102));
        jtf_buscar.setBorder(null);
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jbtn_anterior.setText("Anterior");
        jPanel2.add(jbtn_anterior);

        jbtn_nuevo.setText("Nuevo");
        jPanel2.add(jbtn_nuevo);

        jbtn_actualizar.setText("Actualizar");
        jPanel2.add(jbtn_actualizar);

        jbtn_siguiente.setText("Siguiente");
        jPanel2.add(jbtn_siguiente);

        jbtn_eliminar.setText("Eliminar");
        jPanel2.add(jbtn_eliminar);

        jbtn_agregar.setText("Agregar");
        jPanel2.add(jbtn_agregar);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/coca negro.jpg"))); // NOI18N
        jPanel2.add(jLabel1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 260, 360));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/cocaclasic.jpg"))); // NOI18N
        jPanel1.add(jLabel2);

        jbtn_primero.setText("<<<");
        jPanel1.add(jbtn_primero);

        jbtn_ultimo.setText(">>>");
        jPanel1.add(jbtn_ultimo);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 250, 250));

        jButton1.setText("Buscar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 90, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 130, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 110, -1));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 120, -1));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jLabel3.setText("Precio Compra Pieza");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel4.setText("Precio Compra Paquete de 24");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, -1));

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField2.setBorder(null);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 150, -1));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, -1));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 150, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_clave_proveedor;
    public javax.swing.JLabel jl_contenido;
    public javax.swing.JLabel jl_existencias;
    public javax.swing.JLabel jl_paquete24;
    public javax.swing.JLabel jl_precio_pz;
    public javax.swing.JLabel jl_producto;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_producto;
    public javax.swing.JTextField jtf_clave_proveedor;
    public javax.swing.JTextField jtf_contenido;
    public javax.swing.JTextField jtf_existencias;
    public javax.swing.JTextField jtf_paquete24;
    public javax.swing.JTextField jtf_precio_pz;
    public javax.swing.JTextField jtf_tipo_producto;
    // End of variables declaration//GEN-END:variables
}
