/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewCliente extends javax.swing.JPanel {

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_clave = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellido_p = new javax.swing.JLabel();
        jl_apellido_m = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cliente = new javax.swing.JTable();
        jl_titulo = new javax.swing.JLabel();
        jtf_clave_cliente = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido_paterno = new javax.swing.JTextField();
        jtf_apellido_materno = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_clave.setText("Clave de cliente");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jl_nombre.setText("Nombre ");
        add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jl_apellido_p.setText("Apellido paterno");
        add(jl_apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jl_apellido_m.setText("Apellido Materno");
        add(jl_apellido_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jl_telefono.setText("Telefono");
        add(jl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jt_cliente.setBackground(new java.awt.Color(0, 102, 102));
        jt_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jt_cliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 600, 200));

        jl_titulo.setFont(new java.awt.Font("Microsoft JhengHei", 2, 18)); // NOI18N
        jl_titulo.setText("          Clientes");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 180, 30));

        jtf_clave_cliente.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_cliente.setBorder(null);
        add(jtf_clave_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        jtf_nombre.setBackground(new java.awt.Color(0, 102, 102));
        jtf_nombre.setBorder(null);
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, -1));

        jtf_apellido_paterno.setBackground(new java.awt.Color(0, 102, 102));
        jtf_apellido_paterno.setBorder(null);
        add(jtf_apellido_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 140, -1));

        jtf_apellido_materno.setBackground(new java.awt.Color(0, 102, 102));
        jtf_apellido_materno.setBorder(null);
        add(jtf_apellido_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, -1));

        jtf_telefono.setBackground(new java.awt.Color(0, 102, 102));
        jtf_telefono.setBorder(null);
        add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 20));

        jtf_buscar.setBackground(new java.awt.Color(0, 102, 102));
        jtf_buscar.setBorder(null);
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.setBorder(new javax.swing.border.MatteBorder(null));
        add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 60, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 140, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 112, 140, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 140, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 150, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 10));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/cocaclasic.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/coca negro.jpg"))); // NOI18N

        jbtn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-de-acuerdo-48.png"))); // NOI18N
        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-cancelar-48.png"))); // NOI18N
        jbtn_eliminar.setText("Eliminar");

        jbtn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-agregar-archivo-48.png"))); // NOI18N
        jbtn_nuevo.setText("Nuevo");

        jbtn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-actualizar-48.png"))); // NOI18N
        jbtn_actualizar.setText("Actualizar");

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-siguiente-48.png"))); // NOI18N
        jbtn_siguiente.setText("Siguiente");

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-anterior-48.png"))); // NOI18N
        jbtn_anterior.setText("Anterior");

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-izquierda-en-cuadrado-48 (1).png"))); // NOI18N
        jbtn_primero.setText("Primero");

        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-derecha-en-cuadrado-48.png"))); // NOI18N
        jbtn_ultimo.setText("Ultimo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtn_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_anterior))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_siguiente)
                                    .addComponent(jbtn_actualizar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtn_primero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar)
                    .addComponent(jbtn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_nuevo)
                    .addComponent(jbtn_actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_anterior))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtbn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbn_ultimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_apellido_m;
    public javax.swing.JLabel jl_apellido_p;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_cliente;
    public javax.swing.JTextField jtf_apellido_materno;
    public javax.swing.JTextField jtf_apellido_paterno;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_cliente;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
