/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form ViewUsuarios
     */
    public ViewUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        id_usuario = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_password = new javax.swing.JLabel();
        jtf_id_usuario = new javax.swing.JTextField();
        jl_cargo = new javax.swing.JLabel();
        jl_fecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_usuario = new javax.swing.JTable();
        jtf_nombre = new javax.swing.JTextField();
        jtf_password = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jtf_fecha = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jtf_tipo_usuario = new javax.swing.JTextField();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jl_fondo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_titulo.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        jl_titulo.setText("       Usuarios Registrados ");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 20));

        id_usuario.setText("Clave");
        add(id_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jl_nombre.setText("Nombre");
        add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jl_password.setText("Contraseña");
        add(jl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        add(jtf_id_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 50, -1));

        jl_cargo.setText("Cargo");
        add(jl_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jl_fecha.setText("Facha");
        add(jl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jt_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Contraseña", "Cargo", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jt_usuario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 530, 100));
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, -1));

        jtf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_passwordActionPerformed(evt);
            }
        });
        add(jtf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, -1));

        jbtn_primero.setText("<<<");
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, -1));
        add(jtf_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 150, -1));
        add(jtf_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, -1));

        jbtn_ultimo.setText(">>>");
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 80, -1));

        jbtn_anterior.setText("Anterior");
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jbtn_siguiente.setText("Siguiente");
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jbtn_nuevo.setText("Nuevo");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 70, -1));

        jbtn_actualizar.setText("Actualizar");
        add(jbtn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jbtn_eliminar.setText("Eliminar");
        add(jbtn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jbtn_agregar.setText("Agregar");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, -1));

        jl_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Pictures\\deposito\\images (psco).jpg")); // NOI18N
        add(jl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 250, 230));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_passwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel id_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_cargo;
    public javax.swing.JLabel jl_fecha;
    public javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_password;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_usuario;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_fecha;
    public javax.swing.JTextField jtf_id_usuario;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_password;
    public javax.swing.JTextField jtf_tipo_usuario;
    // End of variables declaration//GEN-END:variables
}
