/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewProducto extends javax.swing.JPanel {

    /**
     * Creates new form ViewProducto
     */
    public ViewProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_clave = new javax.swing.JLabel();
        jl_producto = new javax.swing.JLabel();
        jl_contenido = new javax.swing.JLabel();
        jl_existencias = new javax.swing.JLabel();
        jl_clave_proveedor = new javax.swing.JLabel();
        jl_precio_pz = new javax.swing.JLabel();
        jl_paquete24 = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jtf_clave_producto = new javax.swing.JTextField();
        jtf_tipo_producto = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        jtf_existencias = new javax.swing.JTextField();
        jtf_clave_proveedor = new javax.swing.JTextField();
        jtf_precio_pz = new javax.swing.JTextField();
        jtf_paquete24 = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jl_fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_clave.setText("Clave de producto");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 97, -1, -1));

        jl_producto.setText("Producto");
        add(jl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 136, -1, -1));

        jl_contenido.setText("Contenido");
        add(jl_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 177, -1, -1));

        jl_existencias.setText("Existencias");
        add(jl_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 217, -1, -1));

        jl_clave_proveedor.setText("Clave de Proveedor");
        add(jl_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 258, -1, -1));

        jl_precio_pz.setText("Precio por pz");
        add(jl_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 298, -1, -1));

        jl_paquete24.setText("Precio por paquete24");
        add(jl_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 336, -1, -1));

        jl_titulo.setFont(new java.awt.Font("PMingLiU-ExtB", 2, 14)); // NOI18N
        jl_titulo.setText("Registro de Productos ");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, 146, -1));

        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Producto", "Contenido", "Existencias", "Proveedor", "Precio Pz", "Paquete24"
            }
        ));
        jScrollPane1.setViewportView(jt_productos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 680, 90));
        add(jtf_clave_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 94, 40, -1));
        add(jtf_tipo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 133, 93, -1));
        add(jtf_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 174, 93, -1));
        add(jtf_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 214, 93, -1));
        add(jtf_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 255, 93, -1));
        add(jtf_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 295, 93, -1));
        add(jtf_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 333, 93, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 376, -1, -1));
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 373, 172, -1));

        jbtn_primero.setText("<<<");
        add(jbtn_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 132, -1, -1));

        jbtn_ultimo.setText(">>>");
        add(jbtn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 132, -1, -1));

        jbtn_anterior.setText("Anterior");
        add(jbtn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 173, -1, -1));

        jbtn_siguiente.setText("Siguiente");
        add(jbtn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 173, -1, -1));

        jbtn_nuevo.setText("Nuevo");
        add(jbtn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 213, -1, -1));

        jbtn_actualizar.setText("Actualizar");
        add(jbtn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 213, -1, -1));

        jbtn_eliminar.setText("Eliminar");
        add(jbtn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 254, -1, -1));

        jbtn_agregar.setText("Agregar");
        add(jbtn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 254, 81, -1));

        jl_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Pictures\\deposito\\logopepsi.jpg")); // NOI18N
        add(jl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 490));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_clave_proveedor;
    public javax.swing.JLabel jl_contenido;
    public javax.swing.JLabel jl_existencias;
    public javax.swing.JLabel jl_fondo;
    public javax.swing.JLabel jl_paquete24;
    public javax.swing.JLabel jl_precio_pz;
    public javax.swing.JLabel jl_producto;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_producto;
    public javax.swing.JTextField jtf_clave_proveedor;
    public javax.swing.JTextField jtf_contenido;
    public javax.swing.JTextField jtf_existencias;
    public javax.swing.JTextField jtf_paquete24;
    public javax.swing.JTextField jtf_precio_pz;
    public javax.swing.JTextField jtf_tipo_producto;
    // End of variables declaration//GEN-END:variables
}
