/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("          Proveedores ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 135, 25));

        jLabel2.setText("Clave de Proveedor ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 51, -1, -1));

        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 92, -1, -1));

        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 136, -1, -1));

        jLabel5.setText("Telefono ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 174, -1, -1));

        jLabel6.setText("Compañia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 212, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Telefono", "Compañia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 640, 99));

        jButton1.setText("<<<");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 108, -1, -1));

        jButton2.setText(">>>");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 108, -1, -1));

        jButton3.setText("Anterior");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 171, -1, -1));

        jButton4.setText("Siguiente");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 171, -1, -1));

        jButton5.setText("Nuevo");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 212, -1, -1));

        jButton6.setText("Actualizar");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 212, -1, -1));

        jButton7.setText("Agregar");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 257, -1, -1));

        jButton8.setText("Eliminar");
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 257, -1, -1));

        jLabel7.setText("Buscar");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 286, 127, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 48, 42, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 89, 144, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 133, 144, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 171, 144, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 209, 142, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Pictures\\deposito\\coca-cola-w855h425.gif")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
