/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewProducto extends javax.swing.JPanel {

    /**
     * Creates new form ViewProducto
     */
    public ViewProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_clave = new javax.swing.JLabel();
        jl_producto = new javax.swing.JLabel();
        jl_contenido = new javax.swing.JLabel();
        jl_existencias = new javax.swing.JLabel();
        jl_clave_proveedor = new javax.swing.JLabel();
        jl_precio_pz = new javax.swing.JLabel();
        jl_paquete24 = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jtf_clave_producto = new javax.swing.JTextField();
        jtf_tipo_producto = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        jtf_existencias = new javax.swing.JTextField();
        jtf_clave_proveedor = new javax.swing.JTextField();
        jtf_precio_pz = new javax.swing.JTextField();
        jtf_paquete24 = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jbtn_buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_clave.setText("Clave de producto");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jl_producto.setText("Producto");
        add(jl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        jl_contenido.setText("Contenido");
        add(jl_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jl_existencias.setText("Existencias");
        add(jl_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jl_clave_proveedor.setText("Clave de Proveedor");
        add(jl_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jl_precio_pz.setText("Precio por pz");
        add(jl_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jl_paquete24.setText("Precio por paquete24");
        add(jl_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jl_titulo.setFont(new java.awt.Font("PMingLiU-ExtB", 2, 14)); // NOI18N
        jl_titulo.setText("Registro de Productos ");
        add(jl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, 146, -1));

        jt_productos.setBackground(new java.awt.Color(0, 102, 102));
        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Clave", "Producto", "Contenido", "Existencias", "Proveedor", "Precio comra pz", "Precio  pz", "Precio compra pq24", "Precio paq24"
            }
        ));
        jScrollPane1.setViewportView(jt_productos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 680, 180));

        jtf_clave_producto.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_producto.setBorder(null);
        add(jtf_clave_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        jtf_tipo_producto.setBackground(new java.awt.Color(0, 102, 102));
        jtf_tipo_producto.setBorder(null);
        add(jtf_tipo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, -1));

        jtf_contenido.setBackground(new java.awt.Color(0, 102, 102));
        jtf_contenido.setBorder(null);
        add(jtf_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, -1));

        jtf_existencias.setBackground(new java.awt.Color(0, 102, 102));
        jtf_existencias.setBorder(null);
        add(jtf_existencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        jtf_clave_proveedor.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_proveedor.setBorder(null);
        add(jtf_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, -1));

        jtf_precio_pz.setBackground(new java.awt.Color(0, 102, 102));
        jtf_precio_pz.setBorder(null);
        add(jtf_precio_pz, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, -1));

        jtf_paquete24.setBackground(new java.awt.Color(0, 102, 102));
        jtf_paquete24.setBorder(null);
        add(jtf_paquete24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 120, -1));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jtf_buscar.setBackground(new java.awt.Color(0, 102, 102));
        jtf_buscar.setBorder(null);
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jbtn_buscar.setText("Buscar");
        add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 90, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 130, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 110, -1));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 120, -1));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jLabel3.setText("Precio Compra Pieza");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel4.setText("Precio Compra Paquete de 24");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, -1));

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField2.setBorder(null);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 150, -1));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 100, -1));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 150, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/cocaclasic.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/coca negro.jpg"))); // NOI18N

        jbtn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-de-acuerdo-48.png"))); // NOI18N
        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-cancelar-48.png"))); // NOI18N
        jbtn_eliminar.setText("Eliminar");

        jbtn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-agregar-archivo-48.png"))); // NOI18N
        jbtn_nuevo.setText("Nuevo");

        jbtn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-actualizar-48.png"))); // NOI18N
        jbtn_actualizar.setText("Actualizar");

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-siguiente-48.png"))); // NOI18N
        jbtn_siguiente.setText("Siguiente");

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-anterior-48.png"))); // NOI18N
        jbtn_anterior.setText("Anterior");

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-izquierda-en-cuadrado-48 (1).png"))); // NOI18N
        jbtn_primero.setText("Primero");

        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-derecha-en-cuadrado-48.png"))); // NOI18N
        jbtn_ultimo.setText("Ultimo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtn_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_anterior))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_siguiente)
                                    .addComponent(jbtn_actualizar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtn_primero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar)
                    .addComponent(jbtn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_nuevo)
                    .addComponent(jbtn_actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_anterior))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_primero)
                    .addComponent(jbtn_ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 330, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_clave_proveedor;
    public javax.swing.JLabel jl_contenido;
    public javax.swing.JLabel jl_existencias;
    public javax.swing.JLabel jl_paquete24;
    public javax.swing.JLabel jl_precio_pz;
    public javax.swing.JLabel jl_producto;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_producto;
    public javax.swing.JTextField jtf_clave_proveedor;
    public javax.swing.JTextField jtf_contenido;
    public javax.swing.JTextField jtf_existencias;
    public javax.swing.JTextField jtf_paquete24;
    public javax.swing.JTextField jtf_precio_pz;
    public javax.swing.JTextField jtf_tipo_producto;
    // End of variables declaration//GEN-END:variables
}
