/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author mark
 */
public class ViewProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedores
     */
    public ViewProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_clave = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellido = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_compañia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_proveedor = new javax.swing.JTable();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jtf_clave_proveedor = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_compania = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtn_buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("          Proveedores ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 135, 25));

        jl_clave.setText("Clave de Proveedor ");
        add(jl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jl_nombre.setText("Nombre");
        add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jl_apellido.setText("Apellido");
        add(jl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jl_telefono.setText("Telefono ");
        add(jl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jl_compañia.setText("Compañia");
        add(jl_compañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jt_proveedor.setBackground(new java.awt.Color(0, 102, 102));
        jt_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Telefono", "Compañia"
            }
        ));
        jScrollPane1.setViewportView(jt_proveedor);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 580, 140));

        jl_buscar.setText("Buscar");
        add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jtf_buscar.setBackground(new java.awt.Color(0, 102, 102));
        jtf_buscar.setBorder(null);
        add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, -1));

        jtf_clave_proveedor.setBackground(new java.awt.Color(0, 102, 102));
        jtf_clave_proveedor.setBorder(null);
        add(jtf_clave_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));

        jtf_nombre.setBackground(new java.awt.Color(0, 102, 102));
        jtf_nombre.setBorder(null);
        add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, -1));

        jtf_apellido.setBackground(new java.awt.Color(0, 102, 102));
        jtf_apellido.setBorder(null);
        add(jtf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 144, -1));

        jtf_telefono.setBackground(new java.awt.Color(0, 102, 102));
        jtf_telefono.setBorder(null);
        add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 144, -1));

        jtf_compania.setBackground(new java.awt.Color(0, 102, 102));
        jtf_compania.setBorder(null);
        add(jtf_compania, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 142, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jbtn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-de-acuerdo-48.png"))); // NOI18N
        jbtn_agregar.setText("Agregar");
        jPanel1.add(jbtn_agregar);

        jbtn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-cancelar-48.png"))); // NOI18N
        jbtn_eliminar.setText("Eliminar");
        jPanel1.add(jbtn_eliminar);

        jbtn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-agregar-archivo-48.png"))); // NOI18N
        jbtn_nuevo.setText("Nuevo");
        jPanel1.add(jbtn_nuevo);

        jbtn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-actualizar-48.png"))); // NOI18N
        jbtn_actualizar.setText("Actualizar");
        jPanel1.add(jbtn_actualizar);

        jbtn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-anterior-48.png"))); // NOI18N
        jbtn_anterior.setText("Anterior");
        jPanel1.add(jbtn_anterior);

        jbtn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-siguiente-48.png"))); // NOI18N
        jbtn_siguiente.setText("Siguiente");
        jPanel1.add(jbtn_siguiente);

        jbtn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-izquierda-en-cuadrado-48 (1).png"))); // NOI18N
        jbtn_primero.setText("Primero");
        jPanel1.add(jbtn_primero);

        jbtn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/icons8-derecha-en-cuadrado-48.png"))); // NOI18N
        jbtn_ultimo.setText("Ultimo");
        jPanel1.add(jbtn_ultimo);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/coca negro.jpg"))); // NOI18N
        jPanel1.add(jLabel2);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 280, 410));

        jbtn_buscar.setText("Buscar");
        add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenes/cocaclasic.jpg"))); // NOI18N
        jPanel2.add(jLabel3);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 280, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 102, 150, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 102, 150, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 232, 150, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 150, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_apellido;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_clave;
    public javax.swing.JLabel jl_compañia;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JTable jt_proveedor;
    public javax.swing.JTextField jtf_apellido;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_clave_proveedor;
    public javax.swing.JTextField jtf_compania;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
